@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZTIyM2UyOC01Y2U0LTQxNjgtOTE4Yy0wZjQwZWRjMDc3Y2IiLCJlbWFpbCI6ImpvaG5icmlhbjI0dkBnbWFpbC5jb20iLCJyb2xlIjoiTUFJTl9BRE1JTiIsImlhdCI6MTc3Njk2NzM5NiwiZXhwIjoxNzc3NTcyMTk2fQ.nMF9Rw2vMzQOkuqdyyDX3Plh1sVRkFj3-UoJdGlRjVY



### Create a product (without image upload)
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "fresh pork meat",
  "description": "high quality eggs from local farming",
  "price": 200,
  "quantity": 50,
  "isWholesale": false,
  "stallId": "c28b2b7f-1230-4fc6-bbca-90e7ba1832bc",
  "farmerId": "5c58be2c-ad8d-430f-aab9-4a73e3f3a8b6"
}

### find all
GET http://localhost:3000/products/findALL

### find by id
GET http://localhost:3000/products/ece4d94b-b6da-4e29-98e5-3297d960cd5e
###find by name
GET http://localhost:3000/products/name/fresh pork meat


### Update product
PUT http://localhost:3000/products/ece4d94b-b6da-4e29-98e5-3297d960cd5e
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Fresh potatoes-in-market",
  "description": "Organic potatoes from local farming - updates description",
  "price": 240,
  "quantity": 50,
  "isWholesale": true,
  "status": "APPROVED"
}

### update status
PATCH http://localhost:3000/products/ece4d94b-b6da-4e29-98e5-3297d960cd5e/status
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "status": "REJECTED"
}

###delete product
DELETE http://localhost:3000/products/ece4d94b-b6da-4e29-98e5-3297d960cd5e
Authorization: Bearer {{access_token}}
Content-Type: application/json