
@baseUrl = http://localhost:3000


@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZTIyM2UyOC01Y2U0LTQxNjgtOTE4Yy0wZjQwZWRjMDc3Y2IiLCJlbWFpbCI6ImpvaG5icmlhbjI0dkBnbWFpbC5jb20iLCJyb2xlIjoiTUFJTl9BRE1JTiIsImlhdCI6MTc3Njk2NzM5NiwiZXhwIjoxNzc3NTcyMTk2fQ.nMF9Rw2vMzQOkuqdyyDX3Plh1sVRkFj3-UoJdGlRjVY

####create stall
POST {{baseUrl}}/stall
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "central enterprises",
  "location": "Nakuru",
  "ownerId": "642129f8-aa82-4f97-a2de-b6522126fbed"

}

###findAll
GET http://localhost:3000/stall
Content-Type: application/json
Authorization: Bearer {{access_token}}

###findOne
GET http://localhost:3000/stall/c28b2b7f-1230-4fc6-bbca-90e7ba1832bc
Content-Type: application/json

### Update a Stall (MAIN_ADMIN or STALL_ADMIN only)
PATCH http://localhost:3000/stall/c28b2b7f-1230-4fc6-bbca-90e7ba1832bc
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Fresh Fruits and Vegetables",
  "location": "Central Market",
  "description": "Now with vegetables!"
}


### Delete a Stall (MAIN_ADMIN or STALL_ADMIN only)
GET http://localhost:3000/stall/39382d75-241d-445c-a6a8-19b2650be4c8/delete
Authorization: Bearer {{access_token}}