@baseUrl = http://localhost:3000

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZTIyM2UyOC01Y2U0LTQxNjgtOTE4Yy0wZjQwZWRjMDc3Y2IiLCJlbWFpbCI6ImpvaG5icmlhbjI0dkBnbWFpbC5jb20iLCJyb2xlIjoiTUFJTl9BRE1JTiIsImlhdCI6MTc3Njk2NzM5NiwiZXhwIjoxNzc3NTcyMTk2fQ.nMF9Rw2vMzQOkuqdyyDX3Plh1sVRkFj3-UoJdGlRjVY

### CREATE USER (Admin only)
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "email": "johnbrian24vrt@gmail.com",
  "password":"ADMIN123",
  "name": "ADMIN",
  "role": "MAIN_ADMIN"
}


### CREATE USER (Regular user)
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "email": "peterjurrniordev205@gmail.com",
  "password":"User123",
  "name": "peter",
  "role": "FARMER"
}

### GET ALL USERS
GET {{baseUrl}}/users
Authorization: Bearer {{access_token}}

### Get User by Email
GET {{baseUrl}}/users/email/devpeternjoroge@gmail.com
Authorization: Bearer {{access_token}}

### GET USERS PAGINATED (Admin only) check on this
GET {{baseUrl}}/users/paginated?page=1&limit=5
Authorization: Bearer {{access_token}}

### GET SINGLE USER BY ID (Admin only)
GET {{baseUrl}}/users/642129f8-aa82-4f97-a2de-b6522126fbed
Authorization: Bearer {{access_token}}

### CHANGE PASSWORD (Admin or User)
PATCH {{baseUrl}}/users/e102db35-b4fb-4539-bc43-4c3edafa424c/password
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "currentPassword": "User123",
  "newPassword": "user1234"
}

### curl -X POST {{baseUrl}}/auth/dev/verify-email
POST {{baseUrl}}/auth/dev/verify-email
Content-Type: application/json

{
  "email": "peterjuniordev20@gmail.com"
}

### change role
PATCH {{baseUrl}}/users/15d0cd51-406c-4a1b-aab7-6740b8fb96bd/role
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "role": "STALL_ADMIN"
}

### change customer to courier
PATCH {{baseUrl}}/users/3e747933-ad94-4dff-b913-5bd907917a5d/role
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "role": "MAIN_ADMIN"
}

### delete user
DELETE {{baseUrl}}/users/5c58be2c-ad8d-430f-aab9-4a73e3f3a8b6
Content-Type: application/json
Authorization: Bearer {{access_token}}