@baseUrl = http://localhost:3000

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZTc0NzkzMy1hZDk0LTRkZmYtYjkxMy01YmQ5MDc5MTdhNWQiLCJlbWFpbCI6Im5qdWd1bmFocGV0ZXJuam9yb2dlQGdtYWlsLmNvbSIsInJvbGUiOiJNQUlOX0FETUlOIiwiaWF0IjoxNzU1MDY0MTMyLCJleHAiOjE3NTU2Njg5MzJ9.xDkkK6jq76abQ5wxxx6lonzQ-zzGmfyGA_N6-fDnECo

### CREATE USER (Admin only)
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "email": "peterjuniordev@gmail.com",
  "password":"user123",
  "name": "peter",
  "role": "CUSTOMER"
}

### CREATE USER (Regular user)
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "email": "peterjuniordev@gmail.com",
  "password":"User123",
  "name": "peter",
  "role": "MAIN_ADMIN"
}

### GET ALL USERS
GET {{baseUrl}}/users
Authorization: Bearer {{access_token}}

### Get User by Email
GET {{baseUrl}}/users/email/devpeternjoroge@gmail.com
Authorization: Bearer {{access_token}}

### GET USERS PAGINATED (Admin only)
GET {{baseUrl}}/users/paginated?page=1&limit=5
Authorization: Bearer {{access_token}}

### GET SINGLE USER BY ID (Admin only)
GET {{baseUrl}}/users/642129f8-aa82-4f97-a2de-b6522126fbed
Authorization: Bearer {{access_token}}

### CHANGE PASSWORD (Admin or User)
PATCH {{baseUrl}}/users/15d0cd51-406c-4a1b-aab7-6740b8fb96bd/password
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "currentPassword": "user123",
  "newPassword": "user1234"
}

### curl -X POST {{baseUrl}}/auth/dev/verify-email
POST {{baseUrl}}/auth/dev/verify-email
Content-Type: application/json

{
  "email": "devpeternjoroge@gmail.com"
}

### change role
PATCH {{baseUrl}}/users/{{id}}/role
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "role": "STALL_ADMIN"
}

### change customer to courier
PATCH {{baseUrl}}/users/3e747933-ad94-4dff-b913-5bd907917a5d/role
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "role": "MAIN_ADMIN"
}
